// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPXVwAHpi7qNCBWD9ivEcftabNaD_DIlk',
    appId: '1:408200456427:web:6f6f31c155c44f102676ae',
    messagingSenderId: '408200456427',
    projectId: 'binus-3681e',
    authDomain: 'binus-3681e.firebaseapp.com',
    storageBucket: 'binus-3681e.appspot.com',
    measurementId: 'G-DM3EV53F70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeYfDb0GA1mQnwabtWK2rzeKV_0iGaH6c',
    appId: '1:408200456427:android:897f6f828cac812a2676ae',
    messagingSenderId: '408200456427',
    projectId: 'binus-3681e',
    storageBucket: 'binus-3681e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8w23re8eQZszptzxzyUR4GfwtkHPXBZg',
    appId: '1:408200456427:ios:ee1f11e3e38c3f092676ae',
    messagingSenderId: '408200456427',
    projectId: 'binus-3681e',
    storageBucket: 'binus-3681e.appspot.com',
    androidClientId: '408200456427-8s4ote5voe4o7e9vpg63i1mjmmq4bu6a.apps.googleusercontent.com',
    iosClientId: '408200456427-38voe77jod8fni6u5jth4n6caabp1hai.apps.googleusercontent.com',
    iosBundleId: 'com.example.binusMp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8w23re8eQZszptzxzyUR4GfwtkHPXBZg',
    appId: '1:408200456427:ios:af522c885d12de752676ae',
    messagingSenderId: '408200456427',
    projectId: 'binus-3681e',
    storageBucket: 'binus-3681e.appspot.com',
    androidClientId: '408200456427-8s4ote5voe4o7e9vpg63i1mjmmq4bu6a.apps.googleusercontent.com',
    iosClientId: '408200456427-is7n66fkusj99mc7h1e0tqacrqt3thgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.binusMp.RunnerTests',
  );
}
